# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YQHChatUIDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YQHChatUIDemo

  target 'YQHChatUIDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YQHChatUIDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
